-- Module: __NAME__ - __DESCRIPTION__
--
-- __COPYRIGHT_NOTICE__
-- $Id$

module('ui.ime', package.seeall)
cereja.load_extension("ui\\ime", ui.ime)




-- Module contents...

IME_CMODE_ALPHANUMERIC = 0
IME_CMODE_NATIVE = 1
IME_CMODE_CHINESE = IME_CMODE_NATIVE
IME_CMODE_HANGEUL = IME_CMODE_NATIVE
IME_CMODE_HANGUL = IME_CMODE_NATIVE
IME_CMODE_JAPANESE = IME_CMODE_NATIVE
IME_CMODE_KATAKANA = 2
IME_CMODE_LANGUAGE = 3
IME_CMODE_FULLSHAPE = 8
IME_CMODE_ROMAN = 16
IME_CMODE_CHARCODE = 32
IME_CMODE_HANJACONVERT = 64
IME_CMODE_SOFTKBD = 128
IME_CMODE_NOCONVERSION = 256
IME_CMODE_EUDC = 512
IME_CMODE_SYMBOL = 1024
IME_CMODE_FIXED = 2048
IME_SMODE_NONE = 0
IME_SMODE_PLAURALCLAUSE = 1
IME_SMODE_SINGLECONVERT = 2
IME_SMODE_AUTOMATIC = 4
IME_SMODE_PHRASEPREDICT = 8




-- __END__
